_default:
  vcs: git
  prerequisites:
    - working-copy-check
    - display-last-changes

  version-generator: simple
  version-persister:
    vcs-tag:
      tag-prefix: "{branch-name}_"
  post-release-actions:
    vcs-publish:
      ask-confirmation: true

main:
  version-generator: semantic
  version-persister:
    vcs-tag:
      tag-prefix: ''
  pre-release-actions:
    changelog-update:
      format: semantic
    vcs-commit: ~
